import { mkdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const contractDirectory = path.resolve(scriptDirectory, "..");
const interfaceArtifactPath = path.join(
  contractDirectory,
  "artifacts",
  "src",
  "IBns.sol",
  "IBns.json",
);
const supplementalArtifactPaths = [
  "Bns",
  "BnsResolverFacet",
  "BnsRegistrationFacet",
  "BnsAtomicMutationFacet",
  "BnsNameFacet",
  "BnsAuthorityFacet",
  "BnsDocumentFacet",
  "BnsAliasPaymentFacet",
].map((contractName) =>
  path.join(
    contractDirectory,
    "artifacts",
    "src",
    `${contractName}.sol`,
    `${contractName}.json`,
  ),
);
const abiPath = path.resolve(
  contractDirectory,
  "..",
  "..",
  "components",
  "bns-evm",
  "abi",
  "Bns.json",
);
const solidityBindingPath = path.resolve(
  contractDirectory,
  "..",
  "..",
  "components",
  "bns-evm",
  "abi",
  "BnsBindings.sol",
);

function canonicalType(input) {
  if (!input.type.startsWith("tuple")) {
    return input.type;
  }
  const suffix = input.type.slice("tuple".length);
  return `(${(input.components ?? []).map(canonicalType).join(",")})${suffix}`;
}

function abiKey(entry) {
  const inputs = (entry.inputs ?? []).map(canonicalType).join(",");
  return `${entry.type}:${entry.name ?? ""}(${inputs})`;
}

const interfaceArtifact = JSON.parse(
  await readFile(interfaceArtifactPath, "utf8"),
);
if (!Array.isArray(interfaceArtifact.abi)) {
  throw new Error(
    `Hardhat artifact has no ABI array: ${interfaceArtifactPath}`,
  );
}

const abi = [...interfaceArtifact.abi];
const knownEntries = new Set(abi.map(abiKey));
for (const artifactPath of supplementalArtifactPaths) {
  const artifact = JSON.parse(await readFile(artifactPath, "utf8"));
  if (!Array.isArray(artifact.abi)) {
    throw new Error(`Hardhat artifact has no ABI array: ${artifactPath}`);
  }
  for (const entry of artifact.abi) {
    if (entry.type !== "error" && entry.type !== "constructor") {
      continue;
    }
    const key = abiKey(entry);
    if (!knownEntries.has(key)) {
      knownEntries.add(key);
      abi.push(entry);
    }
  }
}

const expected = `${JSON.stringify(abi, null, 2)}\n`;
const typesSource = await readFile(
  path.join(contractDirectory, "src", "BnsTypes.sol"),
  "utf8",
);
const eventsSource = await readFile(
  path.join(contractDirectory, "src", "BnsEvents.sol"),
  "utf8",
);
const interfaceSource = await readFile(
  path.join(contractDirectory, "src", "IBns.sol"),
  "utf8",
);

function withoutPreamble(source) {
  return source
    .split("\n")
    .filter(
      (line) =>
        !line.startsWith("// SPDX-License-Identifier:") &&
        !line.startsWith("pragma solidity") &&
        !line.startsWith("import "),
    )
    .join("\n")
    .trim();
}

function interfaceBody(source, declaration) {
  const declarationOffset = source.indexOf(declaration);
  if (declarationOffset < 0) {
    throw new Error(`Missing Solidity declaration: ${declaration}`);
  }
  const bodyStart = source.indexOf("{", declarationOffset);
  const bodyEnd = source.lastIndexOf("}");
  if (bodyStart < 0 || bodyEnd <= bodyStart) {
    throw new Error(`Invalid Solidity interface body: ${declaration}`);
  }
  return source.slice(bodyStart + 1, bodyEnd).trim();
}

const expectedSolidityBinding = `// SPDX-License-Identifier: MIT
// Generated by src/apps/bns/hardhat-scripts/sync-abi.mjs. Do not edit.
pragma solidity ^0.8.24;

${withoutPreamble(typesSource)}

interface Bns {
${interfaceBody(eventsSource, "interface IBnsEvents")}

${interfaceBody(interfaceSource, "interface IBns is IBnsEvents")}
}
`;

if (process.argv.includes("--check")) {
  for (const [outputPath, output, label] of [
    [abiPath, expected, "JSON ABI"],
    [solidityBindingPath, expectedSolidityBinding, "Solidity binding ABI"],
  ]) {
    let actual;
    try {
      actual = await readFile(outputPath, "utf8");
    } catch (error) {
      if (error?.code === "ENOENT") {
        console.error(`Committed ${label} is missing: ${outputPath}`);
        process.exitCode = 1;
        continue;
      }
      throw error;
    }
    if (actual !== output) {
      console.error(`Committed ${label} is out of date; run \`npm run compile\`.`);
      process.exitCode = 1;
    }
  }
} else {
  await mkdir(path.dirname(abiPath), { recursive: true });
  await writeFile(abiPath, expected, "utf8");
  await writeFile(solidityBindingPath, expectedSolidityBinding, "utf8");
}
