mod external;
pub mod shlex_example;
mod test_block_hook_point;
mod test_block_process_chain;
mod test_break;
mod test_capture;
mod test_coercion;
mod test_compare_commands;
mod test_env;
mod test_eq;
mod test_exec;
mod test_external_namespace;
mod test_goto;
mod test_if;
mod test_for;
mod test_list;
mod test_string_match_commands;
mod test_var;
