pub mod shlex_example;
mod test_block_process_chain;
mod test_block_hook_point;
mod test_js_external;
mod test_exec;
mod test_env;
mod test_var;
mod test_capture;
mod test_external_namespace;
mod test_invoke;
mod test_goto;
mod test_if;
mod test_list;
mod test_coercion;
mod test_string_match_commands;
mod external;
