[profile.default]
src = "src"
out = "out"
test = "test"
script = "script"
cache_path = "cache"
libs = ["node_modules"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 20
via_ir = true
evm_version = "paris"
fs_permissions = [{ access = "read-write", path = "./" }]

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
