[package]
name = "cyfs-gateway-modules"
version.workspace = true
edition = "2024"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
buckyos-kit.workspace = true
cyfs-acme = { path = "../cyfs-acme" }
cyfs-dns = { path = "../cyfs-dns" }
cyfs-gateway-api.workspace = true
cyfs-gateway-app-lib = { path = "../cyfs-gateway-app-lib" }
cyfs-gateway-lib = { path = "../cyfs-gateway-lib" }
cyfs-sn = { path = "../cyfs-sn" }
cyfs-socks = { path = "../cyfs-socks" }
cyfs-traffic = { path = "../cyfs-traffic" }
cyfs-tun = { path = "../cyfs-tun" }
jsonwebtoken.workspace = true
kRPC.workspace = true
log.workspace = true
name-lib.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true
